In [35]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/sanfrancisco-salary-3-years/SanFrancisco_salary (excel).xlsx
/kaggle/input/sanfrancisco-salary-3-years/SanFrancisco_salary (csv).csv

# Class 11 - Your Name
**Date:** 2024-5-29
**Title:** Analysis of Employee Salaries
**Description:** This dataset includes information on the salaries of San Francisco city employees.

# Display the first 5 rows in the dataset

In [36]:
import pandas as pd

df = pd.read_csv('/kaggle/input/sanfrancisco-salary-3-years/SanFrancisco_salary (csv).csv')
df.head()

,Unnamed: 0,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Department,Department_ML
0,36159,36160,Gary Altenberg,"Lieutenant, Fire Suppression",128808.87,220909.48,13126.31,44430.12,362844.66,407274.78,2012,Fire,4
1,36160,36161,Gregory Suhr,Chief of Police,302578.00,0.00,18974.11,69810.19,321552.11,391362.30,2012,Other,2
2,36161,36162,Khoa Trinh,Electronic Maintenance Tech,111921.00,146415.32,78057.41,53102.29,336393.73,389496.02,2012,Not dep,5
3,36162,36163,Joanne Hayes-White,"Chief, Fire Department",296943.01,0.00,17816.59,72047.88,314759.60,386807.48,2012,Other,2
4,36163,36164,Frederick Binkley,EMT/Paramedic/Firefighter,126863.19,192424.49,17917.18,44438.25,337204.86,381643.11,2012,Other,2

# Display rows from row 40 to 50

In [37]:
df.iloc[40:51]

,Unnamed: 0,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Department,Department_ML
40,36199,36200,Scott Scholzen,Firefighter,109783.86,160418.47,19873.80,41230.89,290076.13,331307.02,2012,Fire,4
41,36200,36201,Ai Kyung Chung,Anesthetist,227221.89,5693.99,16887.90,78554.11,249803.78,328357.89,2012,Medicine,3
42,36201,36202,Pete Fay Jr,"Battlion Chief, Fire Suppressi",176515.48,74246.62,23772.00,53207.72,274534.10,327741.82,2012,Fire,4
43,36202,36203,John Ehrlich,Captain 3,98747.52,1386.38,203735.92,23607.08,303869.82,327476.90,2012,Fire,4
44,36203,36204,Venus Azar,Asst Med Examiner,243271.98,0.00,13708.15,68106.81,256980.13,325086.94,2012,Police,1
45,36204,36205,Denise Schmitt,Deputy Chief 3,263390.60,0.00,819.01,60298.97,264209.61,324508.58,2012,Other,2
46,36205,36206,Jay Huish,Dept Head V,243115.10,0.00,3486.00,77382.62,246601.10,323983.72,2012,Medicine,3
47,36206,36207,Gregory Stangland,EMT/Paramedic/Firefighter,128091.78,133645.42,16130.24,43913.33,277867.44,321780.77,2012,Other,2
48,36207,36208,Arthur Kenney,Asst Chf of Dept (Fire Dept),204032.52,29768.35,34685.53,53152.06,268486.40,321638.46,2012,Fire,4
49,36208,36209,Kevin Taylor,"Battlion Chief, Fire Suppressi",176515.48,71643.89,23352.06,47455.23,271511.43,318966.66,2012,Fire,4
50,36209,36210,Robert Postel,Asst Chf of Dept (Fire Dept),202075.56,48667.42,12813.53,55037.41,263556.51,318593.92,2012,Fire,4

# Find the job title of the highest paid salary (TotalPay)

In [38]:
highest_paid = df[df['TotalPay'] == df['TotalPay'].max()]
highest_paid['JobTitle']

73763    Deputy Chief 3
Name: JobTitle, dtype: object

[](http://)# Find the average BasePay of Executive Contract Employee (JobTitle)

In [39]:
average_basepay = df[df['JobTitle'] == 'Executive Contract Employee']['BasePay'].mean()
average_basepay

259328.45833333334

# Find the sum of OvertimePay for each job title

In [40]:

overtime_sum = df.groupby('JobTitle')['OvertimePay'].sum()

overtime_sum

JobTitle
ACPO,JuvP, Juv Prob (SFERS)            0.000000
ASR Senior Office Specialist       24659.310054
ASR-Office Assistant                 758.610000
Account Clerk                      51364.299987
Accountant I                           0.000000
                                      ...
Wire Rope Cable Maint Sprv        247340.770000
Worker's Comp Supervisor 1             0.000000
Worker's Compensation Adjuster         0.000000
X-Ray Laboratory Aide             348376.709852
Youth Comm Advisor                     0.000000
Name: OvertimePay, Length: 1109, dtype: float64

# Which job title have spend more for OvertimePay (optional)

In [41]:

overtime_sum = df.groupby('JobTitle')['OvertimePay'].sum()

job_title_max_overtime = overtime_sum.idxmax()

job_title_max_overtime

'Transit Operator'

# What is the most common and the least common job in this dataset

In [42]:
susan_currin_job = df[df['EmployeeName'] == 'Susan Currin']['JobTitle']
susan_currin_job

29       Adm, SFGH Medical Center
73789    Adm, SFGH Medical Center
Name: JobTitle, dtype: object

# What is the job title for Susan Currin

In [43]:

# Filter the DataFrame for Susan Currin and retrieve her job title(s)
susan_currin_job = df.loc[df['EmployeeName'] == 'Susan Currin', 'JobTitle'].unique()

# Display the result
susan_currin_job

array(['Adm, SFGH Medical Center'], dtype=object)

# Find the mean , standard deviation and the median for TotalPay in this dataset

In [44]:
mean_totalpay = df['TotalPay'].mean()
mean_totalpay

76130.13223246128

In [45]:
std_totalpay = df['TotalPay'].std()
std_totalpay,

(51269.83938559982,)

In [46]:
median_totalpay = df['TotalPay'].median()
median_totalpay

72630.7

# How many standard deviation does Captain, Fire Suppression highest salary (TotalPay) deviate from the mean 

hint : z index

In [47]:
deviation_from_mean = (highest_totalpay_captain - mean_totalpay) / std_totalpay
deviation_from_mean

4.535603983827814

# What is the highest BasePay in the dataset?

In [48]:
highest_basepay = df['BasePay'].max()
highest_basepay

319275.01

# How many unique job titles are there in the dataset?

In [49]:
unique_job_titles = df['JobTitle'].nunique()
unique_job_titles

1109

# What is the average TotalPay for employees with the job title 'Police Officer'?

In [50]:
average_totalpay_police_officer = df[df['JobTitle'] == 'Police Officer']['TotalPay'].mean()
average_totalpay_police_officer

96670.31978216473